spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rave-list
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwt:
    secret: 27387c6cb58af41bc2c1a53705369fe5c7d52ff9f2631adf37d3072df3c26945
    expirationMs: 3600000
    refreshExpirationMs: 2592000000